on:
  push:
    branches:
      - master
      - devel
    paths:
      - 'facilebio_base/**'
  schedule:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    # https://crontab.guru/ to debug cron syntax
    # run every Monday and Thursday at 1:00 AM Pacific (8 AM UTC)
    # (takes about an hour)
    # - cron: '0 8 * * 1,4'
    - cron: '0 8 * * *'
jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish base to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: facilebio/facilebio_base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: facilebio_base
