on:
  push:
    branches:
      - master
      - devel
    paths:
      - 'facilebio/**'
  schedule:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    # https://crontab.guru/ to debug cron syntax
    # run monday's and thursdays (1,4) at 5:00 AM Pacific Time (which is noon UTC)
    - cron: '0 12 * * 1,4'
  workflow_dispatch:
    inputs:
      dummy:
        description: 'A dummy variable to enable manual workflow execution'
        required: false
        default: 'gitty up'
name: build-facilebio
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-facilebio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish facilebio to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: facilebio/facilebio
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: facilebio
