name: base-build
on:
  push:
    branches:
      - master
      - devel
    paths:
      - 'facilebio_base/**'
  schedule:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    # https://crontab.guru/ to debug cron syntax
    # run every Monday and Thursday at 1:00 AM Pacific (8 AM UTC)
    # (takes about an hour)
    - cron: '0 8 * * 1,4'
  workflow_dispatch:
    inputs:
      dummy:
        description: 'A dummy variable to enable manual workflow execution'
        required: false
        default: 'gitty up'
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: facilebio/facilebio_base
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
              type=ref,event=branch

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMG_NAME }}:latest
          context: facilebio_base
          secrets: |
              "GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}"
